#!/bin/bash
# Module containing misc functions for project: backupmenu 
# Functions: 
# DisplayFunc. exitHandlerFunc, 
# ReadmeFunc, readconfigFunc,  makeDirFunc


# FUNCTION HEADER
# NAME :  exitHandlerFunc 
# DESCRIPTION: error handler deal with user 
# exits and path not found errors and internet failure 
# INPUTS:  $2  filename 
# PROCESS : exitout DEST 1-6  file error
# or bad argument option input
function exitHandlerFunc
{
	#double square brackets without use of quotes on matching pattern 
	#for glob support
	if [[ "$1" = *dest* ]]
	then
		bmtPrintFunc red "Path not found to Destination directory"
	fi
	case "$1" in
			exitout) : ;;
			destination_path_1) bmtPrintFunc red "$BM_DEST_PATH_1" ;;
			destination_path_2) bmtPrintFunc red "$BM_DEST_PATH_2" ;;
			destination_path_3) bmtPrintFunc red "$BM_DEST_PATH_3" ;;
			destination_path_4) bmtPrintFunc red "$BM_DEST_PATH_4" ;;
			destination_path_5) bmtPrintFunc red "$BM_DEST_PATH_5" ;;
			destination_path_6) bmtPrintFunc red "$BM_DEST_PATH_6" ;;
			misc_dir_path) bmtPrintFunc red "Path not found to directory" ;;
			CONFIG_FILE_PATH) bmtPrintFunc red "$CONFIG_FILE_PATH" ;;
			Readme_Path) bmtPrintFuncred  "Missing readme path";;
			Readme) bmtPrintFunc red "Missing Readme file";;
			fileerror) bmtPrintFunc red "File error at :"
				bmtPrintFunc red "$CONFIG_FILE_PATH/$CONFIG" ;;
			*) bmtPrintFunc yellow "Unknown input to error handler";;
	esac
	bmtPrintFunc b_yellow "Goodbye $USER!"
	bmtPromptFunc anykey "and exit." b_green
	if [ "$1" = "exitout" ]
	then
		exit 0 # non-error exit
	fi 
	exit 1
}

# FUNCTION HEADER
# NAME : DisplayFunc
# DESCRIPTION : Function to display main menu
function DisplayFunc
{
bmtPrintFunc b_cyan "Main Menu:"
	local choiceMainVar
	local optionsMArr=(
	"System backup options       "  \
	"xterm terminal" "View/Edit config file"\
	 "Display Readme" "rsync option" "Exit"\
	)
	select choiceMainVar in "${optionsMArr[@]}"
	do
	case "$choiceMainVar" in
			"${optionsMArr[0]}")  # Full system backup
				clear
				readconfigFunc
				bmtPromptFunc anykey "" b_green
				SystemDestFunc
				exitHandlerFunc exitout 
			;;
			
			"${optionsMArr[1]}")  # open a terminal
				xterm -e "cd  && /bin/bash"
				bmtPromptFunc anykey "" b_green
			;;
			
			"${optionsMArr[2]}")  # config file edit or view
				readconfigFunc "USERCALL"
			;;
			
			"${optionsMArr[3]}")  # Display Readme
				ReadmeFunc
			;;
			
			"${optionsMArr[4]}")  # rsync
				clear
				readconfigFunc
				bmtPromptFunc anykey "" b_green
				rsyncFunc
				bmtPromptFunc anykey "" b_green
				exitHandlerFunc exitout
			;;
			
			*) # exit
				exitHandlerFunc exitout 
			;;
	esac
	break
	done

}

# FUNCTION HEADER
# NAME : ReadmeFunc
# DESCRIPTION : Displays Readme to screen 
function ReadmeFunc
{
	local Readme_Path="/usr/share/doc/backupmenu/" # readme
	bmtPromptFunc line "="  b_cyan
	bmtPrintFunc  b_green "Displaying backupmenu README.md file at $Readme_Path"
	cd "$Readme_Path"  || exitHandlerFunc "Readme_path"
	if [ -f README.md.gz  ]
	then
		zless README.md.gz 
	elif [ -f README.md  ] 
	then
		less README.md
	else 
		exitHandlerFunc "Readme"
	fi
	bmtPrintFunc  b_green "Done!" 
	bmtPromptFunc line "="  b_cyan
	bmtPromptFunc anykey "" b_green
}

# FUNCTION HEADER
# NAME : readconfigFunc
# DESCRIPTION:read the config file into program 
# passed USERCALL
# INPUTS $1 USERCALL when called by user
# OUTPUTS : sets paths for backup function 
# PROCESS : read $CONFIG_FILE_PATH/$CONFIG
function readconfigFunc
{
	# check input if called by user from menu or option
	if [ "$1" = "USERCALL" ]
		then
		cd "$CONFIG_FILE_PATH"  || exitHandlerFunc CONFIG_FILE_PATH
		if [ -f "$CONFIG_FILE_PATH/$CONFIG_FILE" ] 
			then
				local choiceCCVar
				bmtPrintFunc  b_green "Do you want to edit or view? [e/V]"
				read -r choiceCCVar
				if [ "$choiceCCVar" = "e" ]
					then
						$EDITOR "$CONFIG_FILE_PATH/$CONFIG_FILE" || exitHandlerFunc fileerror "$CONFIG_FILE_PATH/$CONFIG"
						clear
						bmtPrintFunc  b_green "Exiting config file edit option"
						bmtPromptFunc anykey "and exit backupmenu." b_green
						exit 0
					else
						bmtPrintFunc  b_green  "Custom paths read from file"
						cat "$CONFIG_FILE_PATH/$CONFIG_FILE" || exitHandlerFunc fileerror "$CONFIG_FILE_PATH/$CONFIG"
						bmtPrintFunc  b_green "Done!"
						bmtPromptFunc anykey "" b_green
						return
				fi
			else
				makeConfigFunc
		fi
	fi
	
	# read $CONFIG for system back up paths 
	bmtPrintFunc  b_green "Reading config file $CONFIG_FILE at:-"
	bmtPrintFunc norm "$CONFIG_FILE_PATH"
	bmtPrintFunc norm " "
	cd "$CONFIG_FILE_PATH"  || exitHandlerFunc CONFIG_FILE_PATH
	# check if file there if not use defaults.
	if [ ! -f "$CONFIG_FILE_PATH/$CONFIG_FILE" ]
		then
			makeConfigFunc
		return
	fi
	# shellcheck disable=SC1090
	source "$CONFIG_FILE" || exitHandlerFunc fileerror "$CONFIG_FILE_PATH/$CONFIG_FILE"
	bmtPrintFunc  b_green  "Custom paths read from file"
	bmtPrintFunc norm " "
	cat "$CONFIG_FILE" || exitHandlerFunc fileerror "$CONFIG_FILE_PATH/$CONFIG_FILE"
	bmtPrintFunc norm " "
	bmtPrintFunc  b_green "Done!"
}


# FUNCTION HEADER
# NAME : makeDirFunc
# DESCRIPTION :  makes a directory with time/date stamp and enters it
# Directory used for program output and backups. 
function makeDirFunc
{
	local dirVar=""
	dirVar=$(date  +%d%b%y-%H%M)"$1"
	mkdir "$dirVar"
	cd "$dirVar" || exitHandlerFunc misc_dir_path
	bmtPrintFunc norm "Directory for output made at:-"
	pwd	 
}

# FUNCTION HEADER
# NAME : makeConfigFunc
# DESCRIPTION :  If the config file does not exist provides a option 
# to get a dummy default  from github with curl command.
function makeConfigFunc
{
	bmtPrintFunc b_yellow " Warning :: Config File does not exist"
	bmtPrintFunc norm "Do u want to fetch the dummy default file with curl from github? [y/N]"
	bmtPromptFunc yesno yes # y/N
	case $? in
		0)  # yes
			# check if curl is installed?
			bmtLinuxFunc checkpac "curl" 2
			if [ $? -ne 0 ]
			then
				bmtPrintFunc red "curl"
				bmtPrintFunc yellow "curl is not installed, please install and try again."
				exitHandlerFunc exitout
			else
				bmtPrintFunc b_green "curl is installed, proceeding with fetching config file from github."
			fi
			curl -o backupmenu.cfg  https://raw.githubusercontent.com/gavinlyonsrepo/backupmenu/master/documentation/backupmenu.cfg
			bmtPrintFunc norm "backupmenu.cfg downloaded from github with curl"
			bmtPrintFunc norm "Please Restart."
			exitHandlerFunc  exitout
		;;
		2) # no
			exitHandlerFunc fileerror "$CONFIG_FILE_PATH/$CONFIG_FILE"
		;;
	esac
}
