#!/bin/bash
# Module containing system backup functions project backupmenu.
# Functions: 
# SystemBackFunc SystemTypeFunc pkglistFunc
# rsyncFunc spinFunc

#FUNCTION HEADER
# NAME : SystemBackFunc
# DESCRIPTION: Displays destination directory picker menu to user
function SystemDestFunc
{
			clear
			#get user input for backup
			local optionsBUArr=("$DEST1" "$DEST2" "$DEST3" \
			"Custom" "Exit")
			local choiceBUVar=""
			msgFunc blue "Pick Destination directory for backup"
			select  choiceBUVar in "${optionsBUArr[@]}"
			#check that paths exist and change path to DEST path
			do
			case "$choiceBUVar" in
			
			"${optionsBUArr[0]}")
							if [ ! -d "$DEST1" ]; then
									exitHandlerFunc DEST1 
							fi  
							cd "$DEST1" || exitHandlerFunc DEST1 
							;;				
			"${optionsBUArr[1]}") 
							if [ ! -d "$DEST2" ]; then
									exitHandlerFunc DEST2
							fi  
							cd "$DEST2" || exitHandlerFunc DEST2
							;;	
			"${optionsBUArr[2]}") 
							if [ !  -d "$DEST3" ]; then
									exitHandlerFunc DEST3 
							fi  
							cd "$DEST3" || exitHandlerFunc DEST3 
							;;	
			"${optionsBUArr[3]}")  #custom path read in 	
						local Path1Var=""
						Path1Var=$(dialog --title "Custom backup" --output-fd 1 --begin 1 1 --cancel-label "Exit" --title  "Select Destination path" --dselect / 10 40) 
						case $? in
							0)
								clear
								msgFunc norm " "
								msgFunc norm "Custom Destination  directory:  \"$Path1Var\" "
							;;
							1)
								clear
								msgFunc norm " "
								msgFunc yellow "Exit pressed."
								return
							;;
							255)
								clear
								msgFunc norm " "
								msgFunc yellow "Esc pressed."
								return
							;;
						esac
						cd "$Path1Var" || exitHandlerFunc DEST4 
						;;

			*) return ;;
			esac
			break
			done
			
			#make the backup directory 
			makeDirFunc "-BACKUP" 
			SystemTypeFunc
}

#FUNCTION HEADER
# NAME: SystemTypeFunc 
# DESCRIPTION: Displays the menu which offers backup options to use
# called from  SystemDestFunc
function  SystemTypeFunc
{
			
			local choiceBu2Var=""
			local optionsBu2Arr=("Make copy of MBR or GPT with dd " "Copy of etc dir" \
"Copy of home dir" "Copy of package lists" "Make tarball of all System" "Options 1-5 combined" "Custom Tarball" "Exit")
			msgFunc blue "Pick a Backup option:-"
			select  choiceBu2Var in "${optionsBu2Arr[@]}"
			do
			case  "$choiceBu2Var" in
			"${optionsBu2Arr[0]}"|"${optionsBu2Arr[5]}") #MBR
				msgFunc green "Make copy of MBR or GPT with dd"
				#get /dev/sdxy where currenty filesystem is mounted 
				local myddpathVar=""
				local mbrVar=""
				myddpathVar="$(df /boot/ --output=source | tail -1)"
				#get the partition type 
				mbrVar=$(sudo parted /dev/sda  print | grep -i 'Partition Table' | awk -F": " '{ print $2 }')
				msgFunc norm "Filesystem is mounted  at : $myddpathVar"
				if [ "$mbrVar" = "gpt" ]
				then
					msgFunc norm  "GPT partition table detected : $mbrVar"
					sudo dd if="$myddpathVar" of=hda-gpt.bin bs=512 skip=1 count=33
				elif [ "$mbrVar" = "msdos" ]
				then
					msgFunc norm "Standard MBR partition table detected : $mbrVar"
					sudo dd if="$myddpathVar" of=hda-mbr.bin bs=512 count=1
				else
					msgFunc norm "$mbrVar"
					msgFunc yellow "Unsupported partition table detected, nothing done "
				fi
				
				msgFunc green "Done!"
			;;&
			"${optionsBu2Arr[1]}"|"${optionsBu2Arr[5]}") # etc
				msgFunc green "Make a copy of etc dir"
				sudo cp -a -v -u /etc .
				msgFunc green "Done!"
			;;&
			"${optionsBu2Arr[2]}"|"${optionsBu2Arr[5]}") # home
				msgFunc green "Make a copy of home dir"
				sudo cp -a -v -u /home .
				msgFunc green "Done!"
				sync
			;;&
			"${optionsBu2Arr[3]}"|"${optionsBu2Arr[5]}") # packages list
				mkdir -p "PKGLISTFILES" || exitHandlerFunc DEST4
				cd "PKGLISTFILES" || exitHandlerFunc DEST4
				pkglistFunc 
				cd ..
			;;&
			"${optionsBu2Arr[4]}"|"${optionsBu2Arr[5]}")# system tar
				msgFunc green "Make tarball of all except tmp dev proc sys run"
				sudo tar --one-file-system --exclude=/tmp/* --exclude=/dev/* --exclude=/proc/* --exclude=/sys/* --exclude=/run/* -pzcvf RootFS_backup.tar.gz /
				msgFunc green "Done!"
				sync 
			;;
			"${optionsBu2Arr[6]}") # custom tar
				msgFunc green "custom  Data"
				
					    local Path2Var=""
						Path2Var=$(dialog --title "Custom Source backup" --output-fd 1 --begin 1 1 --cancel-label "Exit" --title  "Select Soucre Directory" --dselect / 10 40) 
						case $? in
							0)
								clear
								msgFunc green "Custom Tarball"
								msgFunc norm "Custom Source directory:  \"$Path2Var\""
								msgFunc norm "Destination : $(pwd)"
							;;
							1)
								clear
								msgFunc norm " "
								msgFunc yellow "Exit pressed."
								return
							;;
							255)
								clear
								msgFunc norm " "
								msgFunc yellow "Esc pressed."
								return
							;;
						esac
						
						msgFunc norm "Do you want to continue? [Y / n]"
						if msgFunc yesno
						then # yes
							if [ ! -d "$Path2Var" ]; then
									exitHandlerFunc DEST4
							fi  
							tar -pzcvf Custom_backup.tar.gz "$Path2Var"
						fi
						msgFunc anykey
						
			;;
			*) return
			;;
			esac
			break
			done
}

#FUNCTION HEADER
# NAME :  pkglistFunc
# DESCRIPTION: Creates a copy of packages list see below.
function pkglistFunc
{
	local pid=""
	msgFunc green "Making a copy of package lists."
	# call spinner function put run in background and save PID
	echo " "
	spinFunc &
	pid=$!
	
	# (1) all packages 
	dpkg --list | grep ^i > all_PKG
	# (2) List native packages installed explicitly 
	apt-mark showmanual > Exp_PKG
	# (3) List packages that are installed but are not available in any installation source 
	deborphan > noinstall_PKG
	# (4) Get a dump of the whole system information - 
	# Prints, Saves or similar the current state of the package management system. 
	apt-cache stats > stats_PKG
	# (5) List packages that were recently added to one of the installation sources,
	aptitude search '~N' > Recent_add_PKG
	# (6) List packages not required by any other package
	deborphan -anp1 > non-Dep_PKG
	# (7) List packages installed automatically (as dependencies)
	apt-mark showauto > auto_Dep_PKG
	# (8) Prints a list of all installation sources including important information like URI, alias etc
	apt-cache policy > Info_Source_PKG
	# (9) list of non-standard repositories in use
	cat /etc/apt/sources.list.d/*.list | grep -v "^#" > non_standard_PKG
	# (10) list Installed packages by size
	aptitude search "~i" --display-format "%p %I" --sort installsize > install_size_PKG
	# (11) list packages by install date 
	grep installed /var/log/dpkg.log > Install_date_1_PKG
	# (12) list packages by install date less data
	grep " install " /var/log/dpkg.log > Install_date_2_PKG
	
	# Stop spin function with PID
	kill $pid
	echo " "
}

#FUNCTION HEADER
# NAME: spinFunc
# DESCRIPTION: Creates an animation spinner for long time taking process.
function spinFunc
{
	spinner=( Ooooo oOooo ooOoo oooOo ooooO oooOo ooOoo oOooo);
	while true; do
		for i in "${spinner[@]}"; 
		do 
			# no new line , \r reset line       
			echo -ne "\r$i";
			sleep 0.2;
		done;
	done
}

#FUNCTION HEADER
# NAME: rsyncFunc
# DESCRIPTION: Carries out rsync utility option 
function rsyncFunc
{
	clear
	msgFunc green "rsync backup utility"
	msgFunc norm "Source & destination are read from config file"
	msgFunc norm "Source: $rsyncsource"
	msgFunc norm "Destination: $rsyncDest"
	msgFunc norm "Do you want to continue? [Y / n]"
	if msgFunc yesno
	then #yes
		sudo rsync -aAXv --delete \
		--exclude={"/dev/*","/proc/*","/sys/*","/tmp/*","/run/*","/mnt/*","/media/*","/lost+found"} \
		"$rsyncsource" "$rsyncDest"
	fi
	msgFunc green "Done!"
}
