#!/bin/bash
#==HEADER==
# Name : backupmenu
# Description:  Backup CLI for debian Linux based distro using cp, Tar and rsync.
# Software : bash shell
# Written : Gavin lyons 
# Software repo URL : https://github.com/gavinlyonsrepo/backupmenu

#==LIBRARY==
#Source the bashmultitool  library 
LIBPATH="/usr/lib/bashmultitool/"
for MYFILE in "$LIBPATH"*;
do
	source "$MYFILE"
done

#==GLOBAL VARIABLES SETUP==
#cyan bright prompt for select menus
PS3="$(printf "\033[36;1m")By your command: $(printf "\033[0m") "

# config file name
CONFIG="backupmenu.cfg"

# check if $EDITOR Environmental variable is set if not set it to nano
# used for modifying config files
if [ -z "${EDITOR}" ]
then 
	export EDITOR="nano"
fi

# Setup the Program Paths aka DESTx destiations 
# DEST1-3 from $CONFIG, Dest4 misc, dest5 config file, dest6 readme,
# dest7 library modules
DEST5="$HOME/.config/backupmenu" # default path for config file
DEST6="/usr/share/doc/backupmenu/" # readme
DEST7="/usr/lib/backupmenu/modules/" #lib modules

#========================
# *****NB  Devel path comment , OUT for production NB *****
#DEST7="../modules/"  
#========================

mkdir -p "$DEST5"

#==FUNCTIONS==
#Source the module files for the functions from the backupmenu library folder
#at /usr/lib/backupmenu/modules/* , Function syntax: nameFunc.
for MYFILE in "$DEST7"*;
do
	source "$MYFILE"
done

#==MAIN CODE==

clear
#Display opening screen title 
bmtPromptFunc line "="  b_cyan

bmtPrintFunc norm "Backup Utility Menu"
bmtPrintFunc norm "$(date +%T" "%d-%a-Week%U-%b-%Y)"
bmtPrintFunc norm "Unix epoch time $(date +%s)     "

bmtLinuxFunc distrocheck
	case $? in
		4)
			bmtPrintFunc  norm "$(dpkg -s backupmenu 2> /dev/null | grep Version)"
		;;
		5)
			bmtPrintFunc norm "$(pacman -Qs backupmenu | head -1 | cut -c 7-20)"
		;;
		*)
			bmtPrintFunc norm "Version 2.3"
		;;
	esac

bmtPromptFunc line "="  b_cyan

while true; do
	cd ~ || exitHandlerFunc DEST4
	DisplayFunc
done


#==END==
