#!/bin/bash
#=========================HEADER==========================================
# Name : backupmenu
# Title : Backup menu
# Version : 2.0-1
# Description:  Backup CLI for debian Linux based distro using cp, Tar and rsync.
# Software : bash shell
# License : MIT expat
# Written : Gavin lyons 
# Software repo URL : https://github.com/gavinlyonsrepo/backupmenu

#======================GLOBAL VARIABLES SETUP=========================
#colours for printf
	RED=$(printf "\033[31;1m")
	GREEN=$(printf "\033[32;1m")
	YELLOW=$(printf "\033[33;1m")
	BLUE=$(printf "\033[36;1m")
	HL=$(printf "\033[42;1m")
	NORMAL=$(printf "\033[0m")

#prompt for select menus
PS3="${BLUE}By your command:${NORMAL}"

# config file name
CONFIG="backupmenu.cfg"

# check if $EDITOR Environmental variable is set if not set it to nano
# used for modifying config files
if [ -z "${EDITOR}" ]
then 
	export EDITOR="nano"
fi

# Setup the Program Paths aka DESTx destiations 
# DEST1-3 from $CONFIG, Dest4 misc, dest5 config file, dest6 readme,
# dest7 library modules
DEST5="$HOME/.config/backupmenu" # default path for config file
DEST6="/usr/share/doc/backupmenu/" # readme
DEST7="/usr/lib/backupmenu/modules/" #lib modules
#DEST7="../modules/"  # *****NB  Devel path comment , OUT for production NB *****
mkdir -p "$DEST5"

#====================FUNCTIONS===============================
#Source the module files for the functions from the cylon library folder
#at /usr/lib/cylon/modules/* , Function syntax: nameFunc.
for MYFILE in "$DEST7"*;
do
	source "$MYFILE"
done
#==================MAIN CODE====================================

clear
#Display opening screen title 
msgFunc line
msgFunc highlight "Backup Utility Menu"
msgFunc norm "$(date +%T-%d-%a-Week%U-%b-%Y)"
msgFunc norm "Unix epoch time $(date +%s)     "
msgFunc norm "$(dpkg -s backupmenu 2> /dev/null | grep Version)"
msgFunc line

while true; do
	cd ~ || exitHandlerFunc DEST4
	DisplayFunc
done


#======================END==============================
